### ISSUE TITLE
Need help for arm

### ISSUE THREAD

**Issue by michaelsmith213** [opuntiaOS-Project/opuntiaOS#38]
hey @opuntiaOS team so I just building opuntiaOS for aarch32(arm) by using this command:
```
./gn_gen.sh --target_cpu aarch32
```
so how to load this on a real device??

**Comment by michaelsmith213** [comment]
pls help me to load this I a real mobile

**Comment by michaelsmith213** [comment]
I am having an old mobile for testing so I needed to load this in it

**Comment by nimelehin** [comment]
If we talk about ARM, currently we have support only for Cortex-A15 Core. During these development stages the main target is QEMU's vexpress-a15, so the set of implemented drivers is limited to run on vexpress-a15.

Currently the goal of the project is to go "deeper" rather than "widely". By that I mean to have a stable, gorgeous project for limited hardware and after that to scale it. So, after implementing the core mechanisms, we could add more drivers for real hardware and tune the kernel to run on specific SoCs.

To go straight: unfortunately, I don't think it's possible to run it on your phone now. As I have said you can try it out on your computer using emulator QEMU.

**Comment by nimelehin** [comment]
Closing it, if you have any other question, feel free to reopen it.
